### ISSUE TITLE
Loadout: Badge doesn't use the color filter again

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#113]
Similar to #48, New loadout update causes the color filter to not appear in in some places, found 3 of them:

Earning a badge from loadout
![200](https://user-images.githubusercontent.com/33488710/33903028-c8133a94-df6e-11e7-93c6-10ac4285dac2.png)

Selecting featured badge
![badgefeature](https://user-images.githubusercontent.com/33488710/33903048-dfbe5d72-df6e-11e7-8c87-5ab9b633ab96.png)

Player hovercard
![hovercard](https://user-images.githubusercontent.com/33488710/33903099-0f9347d8-df6f-11e7-9bc3-250d004fa342.png)

**Comment by ramunecarbonated** [comment]
number 1: cant fix
number 2: cant fix
number 3 is fixable

**Comment by ramunecarbonated** [comment]
fix will be uploaded later today, thanks for reporting.
as for why I cannot fix 1 and 2: this is because the SweetAlert library, out of the box, does not parse HTML. The icon is supplied as a direct image link and the impact this inconsistensy has is too small for me to make our own copy of that library with the required changes: as we use 3rd party CDNs that provide these libraries it will save us some bandwidth, but most importantly, allows us to easily upgrade.

fixing number 3 introduced a funny "quirk", I hope you can notice it: it is barely noticable but when you see it do not that while it is an unintended interaction that I will keep it as is.
