### ISSUE TITLE
VSH: you can lose your winstreak to under 10 people

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#163]
lost my 10ws when i was against 2 other people, found this weird because you can't gain winstreaks when under 10 people so why should you be able to lose it when less than 10 people are on the server?

**Comment by CountSexulus** [comment]
nevermind im retardo and vsh rewrite is gonna be a thing soon eeeee

**Comment by ramunecarbonated** [comment]
It is bit of an oversight and intended since after win streaks were a thing they were not given any QoL adjustments since we wanted to prevent people of gaining these as easy as losing them as per challenge and the fear that it would make matches with low amount of players pointless relating to win streaks.

Nontheless this will definitely be addressed in the rewrite.
