### ISSUE TITLE
Issue with getting SteamID64 from a spray

### ISSUE THREAD

**Issue by haxtonsale** [redsunservers/LoadoutBugTracker#219]
Pressing R on a spray showed up STEAM_ID_STOP_IGNORING_RETVALS instead of a SteamID like it should.
![20180508202324_1](https://user-images.githubusercontent.com/26278199/39773314-575d0fae-5300-11e8-8433-a702101f8b4e.jpg)
Same shit got printed in console:
SPRAY INFORMATION
Spray by: Mülayim ₪ 
SteamID64: STEAM_ID_STOP_IGNORING_RETVALS 

Happened on Raiden on tfdb_spacebox, if that matters.

**Comment by EgocentricPoliceDick** [comment]
It seems this is related to when a client fails to authenticate fully with the Loadout's services when they can't provide a SteamID (it can still be fetched via the `status` command, but the ID64 starting with 7656119 will fail to display because our web services have failed to grab the specific ID64 of the spray's user.)

It's mitigated mostly on core mod tools which will show the ID3 as a backup if the ID64 can not be found, which is what probably needs to be done here.

**Comment by EgocentricPoliceDick** [comment]
and afaik it was the same problem we were having a while back on the mod tools not showing (or using) steamIDs for some clients.

**Comment by ramunecarbonated** [comment]
this output is intended in the docs if the client is not fully authorized or their steamid could not be retrieved, closing as will not be fixed -- instead, the "error" string will be made more user friendly.
