### ISSUE TITLE
Plumber's Growth can still shrink

### ISSUE THREAD

**Issue by DaveFlare** [redsunservers/LoadoutBugTracker#23]
When you normally use the Plumber's Growth it makes you big and then small, but if you interrupt the action of growing big as soon as you get to the biggest state, and then re-taunt right after, you get the effect of the shrinking period without going back to normal size.

You can only reliably do this once in a life, as to do it with someone's help is extremely inconsistent and unreliable, and to try and do it again after getting small will just reset you back to normal size.

A reliable way to replicate this is if you taunt in a respawn room, and wait until you've done the third growth state.  Then you switch classes which resets you back to normal size and then taunt, you get the effects of the shrink but not the effect of being reset back to the normal size.  It doesn't think the Plumber's Growth taunt effect is taking place anymore.

**Comment by ramunecarbonated** [comment]
Due to how the taunt is coded this does not seem easy to fix at this time for us, in addition due to the fact that it is hard to replicate and that its benefits are plausible (it becomes quite obvious when this bug would be abused and would result in the person exploiting this bug being banned, but is it really worth to be abusing a bug like this that you need to try hard on to actually do).

Based on this logic I will leave this as a wontfix.
