### ISSUE TITLE
"Ultimate Team Carry" badge not being awarded on Armstrong(?) + significant lag spikes

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#260]
I got 14 kills in a round in dodgeball on Armstrong but the server got a really bad lag spike right before the round ended (but didn't crash) and I didn't get the badge. The lag spikes continued for a time period afterwards until the server was restarted.

If it means anything, a challenge coin was activated during my round (but not the first time it was activated during the map) and was activated almost every round after, with the lag spikes appearing continuously.

Pretty sure I saw somebody get the badge on Raiden the other day so it may be an issue exclusive to Armstrong.

**Comment by EgocentricPoliceDick** [comment]
Badge data being sent to the database seemed to not be sent during the lagspikes, which seemed to be caused by a very quick inbound attack according to tcpdump.

As the plugin itself awards the badge (which is uploaded every build by ROBOTSUN), this isn't a bug, but rather an unfortunate circumstance. I've manually awarded the badge and marked this issue as "not a bug".
