### ISSUE TITLE
Some playerskins might not be available in strange quality from crate #8

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#271]
According to the crate's tooltip, every playerskin should be obtainable in strange quality from it, though I've yet to see some of them. Of course, it's possible that people could've just been unlucky and just never got to unbox them, but the amount of strange John Henrys out there makes me doubt it, and it wouldn't hurt to check, I guess. Unusuals seem to be fine, though.
The skins I haven't seen in strange quality yet are:

- Muscle Power (I noticed Frosty has one, but I've never seen any other of these)
- Stonewall Jackson
- Stylish Medicine
- The Bounty Hunter
- The Egocentric Police Dick
- **Edit:** The Grandfather

Related minor issue: Sentry Specialist is listed twice in the crate's tooltip.

**Comment by EgocentricPoliceDick** [comment]
I'm looking at the distribution issue you've mentioned right now to verify that the items in question are valid unboxes for the crate in question, I'll further update once I have compiled the data.

Oh, and I've fixed the tooltip.

**Comment by FortyTwoFortyTwo** [comment]
I've seen someone else unboxed Muscle Power, but haven't seen other 4 skins unboxed

**Comment by woisalreadytaken** [comment]
> I've seen someone else unboxed Muscle Power, but haven't seen other 4 skins unboxed
fair, wasn't completely sure about this one

also, I forgot to mention one skin that might be unavailable: The Grandfather

**Comment by EgocentricPoliceDick** [comment]
Seems you were right. Seems the database has reverted back to an earlier copy of itself (likely during that massive fuckshow back when the forum database was corrupted and it affected everything else) and removed the entries that would allow those skins to drop in Strange quality. I've since added them back on and the changes should be applied within the hour automatically.

> also, I forgot to mention one skin that might be unavailable: The Grandfather
That skin wasn't meant to be included in crate 8, so this isn't valid.
 this issue, I can confirm the distribution is just really unlucky (and rare, too.)

**Comment by EgocentricPoliceDick** [comment]
Okay, so:

The actual crate chance stats in the database actually have the items in them. (some of them have several entries to make the skins rarer, in fact) There were, however, one or two skins that didn't appear in the list. That has since been fixed.

Also worth noting that The Grandfather wasn't in the Unusual listings for the crate, either. Also fixed.
Other than that, it just seems like that it's been unlucky unboxes based on RNG, given that the case itself is supposed to be a rare drop.
