### ISSUE TITLE
VSH Rewrite: a few issues with zombie Scouts

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#292]
**General:** They don't take bleed damage, even though the condition is applied and the HUD effect can be seen. They still regenerate health as they hit bosses.

**Boss interactions**

**Painis Cupcake:** This could be intended but also might be an oversight, Painis can eat and heal from Scouts, meaning that using the Battalion's Backup usually just gives him free health. The amount of hp a corpse heals takes both damage dealt as a zombie Scout and whatever they were before becoming one into consideration.

**Seeldier/possibly Seeman and other double bosses:** If a boss dies while another one is still alive and then gets revived from the Batallion's Backup rage, they will respawn as the boss (same class and model, not sure about weapon and hp). If this happens to someone who was a Seeldier minion, they'll respawn as the minion (tiny Soldier, same model, 400 hp, not sure about his weapon). Both of these cases forces them into the red team, as intended.

**Comment by Benoist3012** [comment]
Thanks, now zombies will lose 4% of their health every second.
Also Painis should only heal 50 hp from zombie corpses but due to an issue with how flags were cleared it healed instead based on their previous life damage but this is fixed now.
And finally battalion will no longer resurrect a duo boss, and will properly clear the boss object if the resurrected player was a minion.
