### ISSUE TITLE
A couple of issues with Heartfelt Appreciation

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/LoadoutBugTracker#298]
(i know you're busy with main bc2 stuff but i'm just putting this here before i forget, so push this back or w/e then take a look later. this'll be the last thing i request here in a while i promise)

- The item blocks default thanks voice lines as if it was a sound replacement. Thanks for the help/assisted kill voice lines still play, and the particle effect still shows up in these cases (as intended).

- After most map changes, the particle effect will stop showing up (thanks voice lines are still blocked) for a while, time can range from about 5 minutes to several map changes, reconnecting/refreshing loadout doesn't fix it, but disconnecting and then reconnecting a while later, even if on the same map, most of the time does. This issue only happens if the item was triggered, as simply having it equipped then not using the thanks voice command through the first map allows it to be used in the next map, but then it'll likely break in the following map.

I can't reproduce either issue in my test server so it's not something I can fix with the code I have, sorry

**Comment by woisalreadytaken** [comment]
a little update on the second issue, now that more people have the item: the effect only stops showing for the item owner, others can see it fine. This makes it less of a problem than I thought it was

**Comment by EgocentricPoliceDick** [comment]
Right, I've got some time to work on these now. Gonna take a poke at this.

This one is a bit unique since this is your code being used (albeit audited for nasty things) so it's 100% unaltered. If you think you might know what's causing it, send me a fix privately and I'll get it synced next build. Otherwise I can take a look myself, but no guarantees because it's particle fuckery, and particle fuckery does not go well with TF2 post-Attachables.

**Comment by woisalreadytaken** [comment]
I've tried to find an issue with the code privately again, went through 15 maps alone and with 2 (non-bot) players but it worked as intended every single time, so I really have no idea about what's going wrong with it in red sun
