### ISSUE TITLE
vsh: seeldier minions are eligible for vsh boss badges

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#332]
The minions that seeldier summons can be eligible to get vsh boss badges (sneaky boss, close quarters, etc.) if hale wins that round, regardless if they are alive or not.

Intended behavior is that only the original duo seeman/seeldier are eligible for those badges.

**Comment by woisalreadytaken** [comment]
is this suggestion made with that one vsh_streets session we had in sunday in mind? specifically this, as it's the last time i've seen this happen: https://cdn.discordapp.com/attachments/472537321833496577/538945040693854218/unknown.png

this person was not a minion, he was the Seeldier boss who had died, I was Seeman and won with ~800 hp (i know about this because i gathered info and sent it to 42 as soon as it happened)

I don't think the minions are getting badges, though. I've seen this happen multiple times and it's always been with non-minion bosses who died, but had their duo win the round.

**Comment by FortyTwoFortyTwo** [comment]
As what wo said, it actually because of winning boss team still counts dead boss for badge, which i have fixed it.
https://github.com/EgocentricPoliceDick/VSH-Rewrite/commit/7e10a9b0438bc2a6aa0f74eea9bf8903c306c31c
