### ISSUE TITLE
vsh: medic assist damage doesn't count for score damage

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#334]
the assist damage that medic gets during the round (from healing other players) is not counted at all for the score damage of the medic during that round, only damage that the medic deals himself (with primary/melee) will fill up the score damage counter

(should be like old vsh where some fraction of assist damage is counted as score damage imo)

**Comment by FortyTwoFortyTwo** [comment]
Not going to make assist damage counts as half of total damage, as it seems a bit weird how medic "gain" actual damage while doing nothing but healing one person.
Im more thinking of having ending screen display both total and assist, and calculate whoever 1st-3rd with bp award, with assist counts half of the winner in 1st-3rd

**Comment by FortyTwoFortyTwo** [comment]
Alright, decided that instead of displaying both kills and assist at end, it instead displays "score" which is (damage + (assist / 2)), which makes assist not add into "damage", but "score" instead.
4000/9000 damage badges & bp now takes into "score" instead of damage
https://github.com/EgocentricPoliceDick/VSH-Rewrite/commit/aa4cf1f82770bdfc489def85a81674fa72ca2dc5
