### ISSUE TITLE
Prophunt is fucked (bunch of issues with the plugin)

### ISSUE THREAD

**Issue by CountSexulus** [redsunservers/LoadoutBugTracker#34]
-No low gravity
-Last man standing has a beacon (and his weapons can be seen floating above him)
-Blus can crouch and they become slightly invisible 
-You can cap the CP on some maps
-CP bonus can overheal you, and only restores 75 health instead of back to full health w/o overheal
-During setup, some scouts are stuck in t-pose but then later get turned into props, due to them selecting scout in class menu (edit: sometimes this doesnt happen and they are stuck as t posing scout)
-Pyros can airblast

**Comment by ramunecarbonated** [comment]
Last man standing having beacon is intended.
BLU being able to turn slightly invisible while crouching is also intended.
Overheal op to 75 health is also intended.

I need more info on "During setup, some scouts are stuck in t-pose but then later get turned into props, due to them selecting scout in class menu (edit: sometimes this doesnt happen and they are stuck as t posing scout)"(does this affect the props when the round actually starts?) and "You can cap the CP on some maps"(specific maps?)

**Comment by CountSexulus** [comment]
if you chose scout while in setup time, you will become a t-posed scout instead of a prop, that's basically it. as for specific maps, ask ebbi as he said that you can do that

**Comment by ramunecarbonated** [comment]
I will take a look into these later tomorrow/thursday.



> LMS getting beaconed , blu turning invis and 75 health overheal didnt happen pre jungle inferno so thats why i reported them

That is weird, since these are features we had for a very long time. 👀

**Comment by CountSexulus** [comment]
ok ebbi says arena_ravage_b1 and he reckons that it could be the arena maps causing the problem (ie arena_mapname not ph_mapname)

**Comment by itVictor** [comment]
> That is weird, since these are features we had for a very long time. 👀

LMS getting beacon was removed during the prophunt update around new years 2017 (when prophunt returned after a hiatus where it was crashing the server), I can't find the exact update thread but I definitely know that it was removed because there were mass complaints about it.

overheal and invisibility are features that I've never heard of, and were definitely not present prior to jungle update (I haven't played ph since before then so I can't really comment if those are worth keeping)

**Comment by ramunecarbonated** [comment]
>LMS getting beacon was removed during the prophunt update around new years 2017 (when prophunt returned after a hiatus where it was crashing the server), I can't find the exact update thread but I definitely know that it was removed because there were mass complaints about it. (imo it should stay disabled)

The beacon is a default feature from PropHunt, the health+75 and crouching invisibility is custom. I do not intend on changing this behaviour but merely to fix the bugs mentioned.

**Comment by ramunecarbonated** [comment]
shoutout to ex-admins for never committing their changes

dead ass

**Comment by ramunecarbonated** [comment]
(Should have) fixed the following:

- No low gravity
- You can cap the CP on some maps
- Pyros can airblast
