### ISSUE TITLE
Delayed voicelines on STT (Spy)

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#352]
I noticed that spy normal voicelines when he is a robot in STT (in-game voicelines and not redsun's) are slightly delayed, around 1 or 2 seconds after the button press and he will then say it. It seems to only apply on spy and not the other mercenarys.

**Comment by FortyTwoFortyTwo** [comment]
Due to how source works, all sounds from sourcemod need to be precache before allowing to be played.
On how STT is done, once you played a sound, sound file is changed to use MvM version, then precache that sound which that takes 1-2 seconds to allow sound be played.

If we want to fix the delay, at map start we would have to precache every single MvM sounds replaced from every voicelines, which there is a lot to list and keep track of only to fix small delay, which isn't really worth at this point.
