### ISSUE TITLE
Sandwich lament "No" doesn't override every no sound in chat

### ISSUE THREAD

**Issue by UrUgli** [redsunservers/LoadoutBugTracker#363]
So i think it's intentional, but saying No in chat with the sandwich lament equipped turns all "No" normal voicelines into the "No" sandwich lament sound. Except some voicelines actually bypass this, sometimes you will hear the normal sniper "no" and a normal pyro "no".

**Comment by FortyTwoFortyTwo** [comment]
Can't reproduce it myself, tried sandwich lament and spamming no saysound as pyro & sniper

**Comment by Zane-Truesdale** [comment]
I have had this happen to me from time to time, though it was with Robotnik and not Sandwich Maker's Lament. Have also had it happen in chat with the DK Thanks replacement and the Bison Yes.

Only reason I didn't post the issue myself is because of how rarely it happens. Most of the times it has, it was during or immediately after a loadout refresh
