### ISSUE TITLE
Gravity entities ignore wall/collisions

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [redsunservers/LoadoutBugTracker#372]
It said that it start happening in VSH Painis round (body entities), but can't confirm that.
Grenades, stickies, sandman ball, any kind of entities affected by gravity just ignores wall/collisions, endlessly falling down into void.
Likely to do with one of the convar as it carries over next map, which requires server restart to fix it.

**Comment by Kenzzer** [comment]
It's actually not a convar or command, or any particular game settings.
This issue is simply a memory corruption, perhaps a bad object size or whatever. The point is, it will carry over maps and continue until the server.. well crash or is restarted before.

The only current fix that could be made is to limit the number of `prop_ragdoll ` alive at once. It seems that the vphysics only start to collapse if 8 `prop_ragdoll` are spawned at once.

A proper fix is to simply study `CRagdollProp` class and find the corruption source.
`https://github.com/alliedmodders/hl2sdk/blob/sdk2013/game/server/physics_prop_ragdoll.cpp`

**Comment by FortyTwoFortyTwo** [comment]
Thanks for the info about it! As what you've suggested i've added max of 8 bodies allowed in map, if it extends limit the oldest bodies will get killed/removed from map
