### ISSUE TITLE
STT: Sentry Buster does not function when nearly killed

### ISSUE THREAD

**Issue by unitgg** [redsunservers/LoadoutBugTracker#39]
POV Demo: https://stack.waal.me/s/y7YUc5miHYd1FcP

Situation of when it happened:
On Moonbase map; team Robots; pre-tank destruction phase iirc.

Description of the issue:
Became Sentry Buster, ran up to enemy team, tried to self-destruct, lost a lot of health during animation to 23 HP and then got stuck at that amount, movement keys don't work except for duck and jump.

**Comment by Benoist3012** [comment]
@unitgg when you were stuck at 23hp did you explode after a while or not? I suppose no

**Comment by unitgg** [comment]
Nope I killed myself.

**Comment by ramunecarbonated** [comment]
It appears that an entity property that is being used by the plugin is not there anymore / is available inconsisently-- said usage is called very early in the code so that makes a Sentry Buster completely broken no matter if you taunted due to HP or manually.
Fix is there but to be deployed at a later time. Thanks for reporting!
