### ISSUE TITLE
Skins are being carried over during class warfare

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#87]
![image](https://user-images.githubusercontent.com/33851923/33535575-33121e86-d863-11e7-8fad-bcf64787ce78.png)

**Comment by itVictor** [comment]
somewhat similar but same issue is still happening in gungame (as in skins persisting through level ups)

**Comment by ramunecarbonated** [comment]
#65 #20 #11 

yeah i am gonna just go back to the old lazy way of resetting skins @Benoist3012

**Comment by Benoist3012** [comment]
@ramunecarbonated let me attempt to fix the issue and if it doesn't work you do your lazy fix.

**Comment by ramunecarbonated** [comment]
@Benoist3012 the thing is that the undo-ing of resetting the model path was unnecessary because in STT (where it broke in the first place) it was because due to an update or some sort the convar wasnt set for the player skin functions to be completely skipped over the robot team(s), so i rather put lazy 1st which proves to work and if you have a better method then we change it to that: but it bleeds into other gamemodes since the general clause on how redsun_playerskins was build on to reset a player's model if they had no skin on their class was pretty needed
